ktor:
  application:
    modules:
      - org.sonic.ApplicationKt.module
  deployment:
    port: 8080
    host: "0.0.0.0"

  database:
    host: ${DB_HOST:127.0.0.1}
    port: ${DB_PORT:5432}
    name: ${DB_NAME:db_sonic}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jwt:
    secret: ${JWT_SECRET:VrrQISTjQiDFsQ2MF794w4cFaQo2daqzGLuMpA+eWng=}

  app:
    baseUrl: ${APP_URL:"http://localhost:8080"}